version: '3'
services:
  poke-cheat:
    build: .
    volumes:
      - ./share/:/root/cheat/share/
      - ./pokeplg/:/root/cheat/pokeplg/ # ここにチートが生成される
    working_dir: /root/cheat/share/
    # Use this for debugging
    # command: /bin/bash -c "while true; do sleep 1000; done"
    # sleep 1 を入れないとファイルが実際に変更される前にビルドが走ってしまう
    command: /bin/bash -c "python3 build.py && while inotifywait -e modify,moved_to,moved_from,create,delete -r .; do sleep 1 && python3 build.py; done"
